### ISSUE TITLE
error

### ISSUE THREAD

**Issue by BrightMoonInner** [Lkhsss/163music-autocheckin#1]
my dear dalao,something was wrong so i come to get your help,thank you
<img width="732" alt="screenshot" src="https://user-images.githubusercontent.com/88758484/197375534-a968fe8b-ab8e-4d5c-9283-97a1e399bf15.png">

**Comment by Lkhsss** [comment]
> my dear dalao,something was wrong so i come to get your help,thank you <img alt="screenshot" width="732" src="https://user-images.githubusercontent.com/88758484/197375534-a968fe8b-ab8e-4d5c-9283-97a1e399bf15.png">

额，看起来是命令的问题
这样，你可以直接从
![image](https://user-images.githubusercontent.com/89461157/197375658-0d76a89f-70bb-4274-bfcd-cd49ec803b3f.png)
这个路径中把163music.pkl复制到项目的主目录中就可以了

**Comment by Lkhsss** [comment]
> my dear dalao,something was wrong so i come to get your help,thank you <img alt="screenshot" width="732" src="https://user-images.githubusercontent.com/88758484/197375534-a968fe8b-ab8e-4d5c-9283-97a1e399bf15.png">

等我这周研究一下，把扫码登陆搞出来

**Comment by Lkhsss** [comment]
> 

# 好啦，问题解决啦
## 看看README,再去试试吧
### 有问题欢迎来问我，没问题了记得给我说一声

**Comment by BrightMoonInner** [comment]
thank you very much.
sorry, but i couldn't find my QR code to scan.it should have worked like this picture,
![扫码登陆](https://user-images.githubusercontent.com/88758484/197438276-0f4a0e72-4648-4d43-9782-d00117299ddc.png)

however, it performed like the img below
<img width="734" alt="screen" src="https://user-images.githubusercontent.com/88758484/197438247-d95b5fbe-353a-4399-984a-40afb5da2334.png">

**Comment by BrightMoonInner** [comment]
i have got the two files in the folder
<img width="231" alt="screen2" src="https://user-images.githubusercontent.com/88758484/197438739-ffe83fb9-0525-4125-9a06-29c92a5468ea.png">

**Comment by BrightMoonInner** [comment]
and this is my config.cfg
<img width="1156" alt="screen3" src="https://user-images.githubusercontent.com/88758484/197438848-f09b7690-6749-45ec-bd35-aa09fefeb985.png">

**Comment by BrightMoonInner** [comment]
sorry for taking your time, thank you

**Comment by Lkhsss** [comment]
sorry i'm not home and the school won't allow me to go back home until Saturday.
if you have music163.pkl, you can just put it in the main folder（the folder which have main.py） and upload the whole folder to the github

**Comment by Lkhsss** [comment]
i'm very happy to answer your questions
but sorry I'm inconvenient.
please forgive my poor english (doge)

**Comment by BrightMoonInner** [comment]
ok, it doesn't matter, thank you very much, you can continue your study without responding to my message, and your english is good
